name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello Bro
        run: echo "Hello from GitHub Actions! hehe"
